### ISSUE TITLE
Jetson Tx2 / Roboclaw 

### ISSUE THREAD

**Issue by Rafcin** [rpanther/panther#1]
Im wondering, is it possible to rework the panther or dude code to be compatible with a Roboclaw motor controller? Also a Zed and a Sweep lidar? I've been looking over your designs/code when trying to build a robot, ROS is really odd to work with for the first time.

**Comment by rbonghi** [comment]
Hi @Rafcin,

The code of Panther and Dude are compatible with Roboclaw and Sweep, but you must substitute in my bringup my rplidar and roboteq/unav loader.

If you want other information write me on raffaello@rnext.it ;-)
