### ISSUE TITLE
what are the sensors used?

### ISSUE THREAD

**Issue by xuduo18** [rpanther/panther#3]
Hello Raffaello,

I can't find details on your website about the use of 
1.  LIDAR Slamtec: https://www.slamtec.com/
2.  IMU

My understanding is ZED alone is good enough to create map and navigate with.

Did you use these 2 extra sensors? 

Thanks!!

**Comment by rbonghi** [comment]
Hi @xuduo18 

The IMU is used with ZED and the motor controller ([Roboteq_control](https://github.com/rbonghi/roboteq_control)) to localize the robot in the environment with robot localization http://wiki.ros.org/robot_localization

The same information from ZED and LIDAR are used to build maps with:
- gmapping: https://github.com/rbonghi/panther/blob/master/panther_navigation/launch/gmapping_demo.launch
- RTAB-Map: https://github.com/rbonghi/panther/blob/master/panther_navigation/launch/rtabmap.launch
- cartographer: https://github.com/rbonghi/panther/blob/master/panther_visualization/launch/cartographer_reader.launch

The same information from ZED are used with darknet to know the information about the environment (objects, people, etc)

**Comment by xuduo18** [comment]
Thanks so much!  A few more questions if you don't mind...

1.  I have read from rtap-map forum that IMU could have lots of noise due to vibration of the robot if on rough terrain, such as lawn.  Do you have the same issue?
2.  you meant that gmapping or rtab-map or cartographer, right? Or do you mean to fuse all of them to one map?
3.  Do you think without LIDAR the result would be similar or close as in your demo video?
4.   I don't see how darknet is used in git repo. Is it not updated?

**Comment by Rafcin** [comment]
I second that question
1. Are you making maps with all 3 systems?
2. How are you using RTAB without it pausing to recover orientation, and with the zed the odom from RTABMAP tends to be very wrong.
3. How do you compensate for drift? And if you use ZED + Lidar odom, how do you use the motors without encoders, like in my case I use a roboclaw controller on servos without encoders and I can't wrap my head around the robot calculation when to run them without encoder data, but are encoders the right thing to have if I drive around in grass?

**Comment by Rafcin** [comment]
*Edit* I can understand how it can move without encoders but say in a grass environment do I really need them?

**Comment by xuduo18** [comment]
Interesting. Are you trying to make it work properly on the lawn?

**Comment by Rafcin** [comment]
And open field, a park. But with obstacles.

**Comment by rbonghi** [comment]
Hi @Rafcin, I reply just now :)
> Are you making maps with all 3 systems?
I’m using, depends of the case:
* gmapping
* rtabmap 
* cartographer 

I don’t use these system together in the same time 
> How are you using RTAB without it pausing to recover orientation, and with the zed the odom from RTABMAP tends to be very wrong.

> How do you compensate for drift? And if you use ZED + Lidar odom, how do you use the motors without encoders, like in my case I use a roboclaw
I’m using the robot localization package (with unscented kalman filter). From odometry I take use the linear velocity (from a tracked robot, the drift is really high)

Depend of your type of robot, but I suggest to use the ZED visual odometry combined with another sensor, but the context is really important to understand which is the better.
> controller on servos without encoders and I can't wrap my head around the robot calculation when to run them without encoder data, but are encoders the right thing to have if I drive around in grass?
The information from encoder in a wheeled robot make a bit more sense in an flat environment, no dirty, really well calibrated, etc etc etc.
In a real context it’s better to use a combination of different exteroceptive sensors.

Raffaello Bonghi

**Comment by rbonghi** [comment]
Hi @xuduo18 

> 1. I have read from rtap-map forum that IMU could have lots of noise due to vibration of the robot if on rough terrain, such as lawn.  Do you have the same issue?

I'm using the robot_localization to filter more data before to send the odometry to rtabmap: http://wiki.ros.org/robot_localization

> 2. you meant that gmapping or rtab-map or cartographer, right? Or do you mean to fuse all of them to one map?

I'm using gmapping, rtab-map or cartographer not in the same time. Depend with the experiment I'm following

> 3. Do you think without LIDAR the result would be similar or close as in your demo video?

Yes I've a test without lidar with only ZED in my room and the result are not good. I think the problem is the camera viewing angle and the environment lights.

Example with gmapping
![ukf zed](https://user-images.githubusercontent.com/4551246/47988245-112a0f80-e0e2-11e8-8541-05feb1a44552.png)
UKF + ZED
![ukf zed lidar](https://user-images.githubusercontent.com/4551246/47988461-8c8bc100-e0e2-11e8-8daf-c1469ea86a11.png)
UKF + ZED + LIDAR

> 4. I don't see how darknet is used in git repo. Is it not updated?

Yes, I'll update soon

**Comment by rbonghi** [comment]
> _Edit_ I can understand how it can move without encoders but say in a grass environment do I really need them?

Agree!
I'm using the encoder to fix speed and torque (with current sensor) but it's not really need for localization
