### ISSUE TITLE
URDF Creation

### ISSUE THREAD

**Issue by Rafcin** [rpanther/panther#4]
Hey I was curious, what steps did you take to create the URDF for the robot? Did you model STL files, and assemble them in a tool?

**Comment by rbonghi** [comment]
Hi @Rafcin,
In the first time, in particular with [Dude](https://github.com/rbonghi/4UDE) I used: http://wiki.ros.org/sw_urdf_exporter.
After I preferred to write by hand my URDF project from solidworks.

The URDF (with xacro) was more clear than automatically written
